### PR TITLE
Retry print-house uploads up to 5 times

### PR DESCRIPTION
**Pull request by gjvis**
Adds naïve fault tolerance to the print-house uploads. A more sophisticated implementation would add random exponential backoff, but I'm not sure its needed in this case. Thoughts?

### CODE REVIEW

**Comment by gjvis** [comment]
Could add another gem (https://github.com/kamui/retriable) that looks to provide more sophisticated rety logic. It doesn't have any runtime dependancies, and seems pretty small and focussed...

**Comment by gjvis** [comment]
Ok, I've added it - I think its worth it considering the small overhead. Compare the commits for the two options and let me know what you think.

**Comment by gjvis** [comment]
Rebased now that logging is merged in, and added logging for errors when retrying.

@andrewgarner, @stevenwilkin :eyes: please

**Comment by andrewgarner** [comment]
:+1:

**Pull request merged**
