### PR TITLE
Output document stylesheet ERB

### PR DESCRIPTION
**Pull request by stevenwilkin**

### CODE REVIEW

**Comment by gjvis** [comment]
If we make the `<style>` tags the responsibility of this method, then we're free to rather inject a `<link>` tag instead without changing the templates. I think this will make refactoring the `OutputDocument` to isolate rendering responsibilities easier.

**Comment by stevenwilkin** [comment]
Good call @gjvis

**Comment by stevenwilkin** [comment]
Done

**Comment by gjvis** [comment]
:+1: :shipit:

**Pull request merged**
