### PR TITLE
Require strong passwords

### PR DESCRIPTION
**Pull request by andrewgarner**
Set fairly conservatively but will reject simple passwords.

### CODE REVIEW

**Comment by stevenwilkin** [comment]
If a password is deemed not string enough is it obvious how to make it stronger?

**Comment by andrewgarner** [comment]
The error message reads "Consider adding a number, symbols or more letters to make it stronger."

**Comment by gjvis** [comment]
We should also add some descriptive text to the "change password" views.

**Comment by andrewgarner** [comment]
I've added the missing devise views for invitations (the only point passwords are set).

I've added some tips on how to create a strong password.

**Comment by gjvis** [comment]
on :fire: 

:+1:

**Pull request merged**
