### PR TITLE
Record whether pension pots value is approximate

### PR DESCRIPTION
**Pull request by gjvis**
Dependent on https://github.com/guidance-guarantee-programme/output/pull/76

### CODE REVIEW

**Comment by andrewgarner** [comment]
This can be rebased now. Needs to be merged once #76 has been deployed to production.

**Comment by gjvis** [comment]
Its already based on #76, just waiting on thumbs to deploy them both

**Comment by andrewgarner** [comment]
Are you sure? You don't need 5e60e21.

**Comment by gjvis** [comment]
*points at commit list*

**Comment by gjvis** [comment]
oh we'd lose the commit bubble though, i'll rebase it over the merge commit for #76 and deploy once i've deployed #76

**Pull request merged**
