### PR TITLE
[WIP] HTML preview of output document

### PR DESCRIPTION
**Pull request by stevenwilkin**
@aduggin's front-end magic is going into this

### CODE REVIEW

**Comment by aduggin** [comment]
I've tweaked the template logic and Matt has confirmed the correct pages are displayed in all scenarios

**Comment by andrewgarner** [comment]
Can we look into the failing tests?

**Comment by stevenwilkin** [comment]
I'll fix the tests now @andrewgarner and then merge the branch in

**Comment by stevenwilkin** [comment]
Tests fixed, good to merge chaps?

**Pull request merged**
