### PR TITLE
Postcode lookup

### PR DESCRIPTION
**Pull request by gjvis**
Adds postcode lookup with fallback address search, based on ideal-postcodes.co.uk

### CODE REVIEW

**Comment by gjvis** [comment]
ping @andrewgarner @stevenwilkin @aduggin, this is now good to go

**Comment by andrewgarner** [comment]
Did we think about a full address search - http://jsfiddle.net/ideal_postcodes/061s9zm8/

**Comment by gjvis** [comment]
Yes: https://github.com/guidance-guarantee-programme/output/commit/16f15da32ea093a68345117286702f31ed0ebcaa

**Comment by andrewgarner** [comment]
Love it! :+1:

**Comment by stevenwilkin** [comment]
:+1:

**Comment by gjvis** [comment]
Just realised that I haven't sorted out the API key stuff, doh! Will do it as a seperate PR.

**Pull request merged**
